#!/usr/bin/env python3
"""Fig: offline dose-response (paper §V, fig:doseresponse) — pgfplots.

Emits paper/figs/dose_response.tex (a tikzpicture, \\input from 5_offline.tex).
One panel: cancellation of committed descent (%) vs forced wrench magnitude
(8/10/12 N) for the four ablation policies (P3, EVIDENCE §3.7 사중 대조):

  conditioned  fromnaive v2 best   grounded bottleneck — monotone, crosses
                                   full cancellation at 12 N (31% -> 115%)
  naive        naive best@10k      template — fades with dose (36 -> 31 -> 28%)
  unmasked     mask0fn_main        raw + dead c-hat — lies on the naive curve,
                                   all response through the raw route
  ungrounded   v1_main             bottleneck, shuffled c-hat — flat at zero

Numbers are parsed from the probe logs' "ALL frames" decomposition line
(mean dTotal / |mean dz(own)|), the same aggregation EVIDENCE §3.7 quotes.
naive/fromnaive logs pool n=245 descent frames, mask0fn/v1 n=739 — a known
artifact of policy-dependent descent-frame selection (EVIDENCE: 상쇄율 결론
무관). Only ramp8/10/12 for naive; the others were probed at 8/12 N.
"""
import re
from pathlib import Path

PROBES = Path("/home/maverick/Humanoid/Dexmate/LGES/vla_training/probes")
OUT = ("/home/maverick/Humanoid/Dexmate/Research/Paper_writing/FiLM/paper/figs/"
       "dose_response.tex")

SERIES = [  # (label key, file stem template, doses)
    ("conditioned", "0729_state_fromnaive_best_ramp{d}", (8, 12)),
    ("naive", "0729_state_naive_ramp{d}", (8, 10, 12)),
    ("unmasked", "0729_state_mask0fn_main_ramp{d}", (8, 12)),
    ("ungrounded", "0729_state_v1_main_ramp{d}", (8, 12)),
]

ALL_RE = re.compile(r"ALL frames\s*:\s*n=\s*\d+\s*dz\(own\)=\s*([+-]?\d+\.\d+)mm"
                    r"\s*dTotal=\s*([+-]?\d+\.\d+)mm")


def cancellation_pct(stem: str) -> float:
    text = (PROBES / f"{stem}.txt").read_text(errors="replace")
    m = ALL_RE.search(text)
    if m is None:
        raise SystemExit(f"no 'ALL frames' line in {stem}.txt")
    own, total = float(m.group(1)), float(m.group(2))
    return 100.0 * total / abs(own)


data = {name: [(d, cancellation_pct(tmpl.format(d=d))) for d in doses]
        for name, tmpl, doses in SERIES}
for name, pts in data.items():
    print(f"  {name:12s}", "  ".join(f"{d}N {p:+.0f}%" for d, p in pts))


def coords(pts):
    return " ".join(f"({d},{p:.1f})" for d, p in pts)


L = []
L.append("% AUTO-GENERATED by scripts/make_dose_response_pgf.py — do not edit.")
L.append("% Data: LGES/vla_training/probes/0729_state_*_ramp*.txt ('ALL frames'")
L.append("% decomposition line); policy mapping per EVIDENCE §3.7 quadruple control.")
L.append(r"\definecolor{figcond}{HTML}{0072B2}")
L.append(r"\definecolor{fignaive}{HTML}{D55E00}")
L.append(r"\definecolor{figmuted}{HTML}{767676}")
L.append(r"\begin{tikzpicture}")
L.append(r"\begin{axis}[")
L.append(r"  width=7.9cm, height=5.0cm, xmin=7.3, xmax=13.7, xtick={8,10,12},")
L.append(r"  ymin=-14, ymax=128, ytick={0,25,50,75,100},")
L.append(r"  xlabel={forced wrench magnitude (N)},")
L.append(r"  ylabel={cancellation of committed descent (\%)},")
L.append(r"  tick label style={font=\scriptsize}, label style={font=\scriptsize},")
L.append(r"  axis x line*=bottom, axis y line*=left,")
L.append(r"  axis line style={figmuted!60, line width=0.4pt},")
L.append(r"  tick style={figmuted!60},")
L.append(r"  ymajorgrids, grid style={figmuted!22, line width=0.3pt},")
L.append(r"  clip=false,")
L.append(r"]")
L.append(r"\addplot[figmuted, dash pattern=on 3pt off 2pt, line width=0.5pt]"
         r" coordinates {(7.3,100) (13.7,100)};")
L.append(r"\node[font=\tiny, figmuted, anchor=south west] at (axis cs:7.45,100)"
         r" {full cancellation (net retreat above)};")

STYLE = {
    "conditioned": ("figcond", "solid", "mark=*, mark options={fill=figcond,"
                    " draw=white, line width=0.3pt}"),
    "naive": ("fignaive", "solid", "mark=*, mark options={fill=fignaive,"
              " draw=white, line width=0.3pt}"),
    "unmasked": ("fignaive", "dash pattern=on 3pt off 2pt", "mark=o,"
                 " mark options={solid, line width=0.5pt}"),
    "ungrounded": ("figmuted", "solid", "mark=*, mark options={fill=figmuted,"
                   " draw=white, line width=0.3pt}"),
}
for name, pts in data.items():
    color, dash, mark = STYLE[name]
    L.append(rf"\addplot[{color}, {dash}, line width=0.9pt, {mark},"
             rf" mark size=1.4pt] coordinates {{{coords(pts)}}};")

# direct labels: conditioned/naive/ungrounded at the right end; unmasked above
# its 8 N point (its 12 N end coincides with the naive curve)
end = {name: pts[-1][1] for name, pts in data.items()}
L.append(rf"\node[font=\scriptsize, figcond, anchor=west] at"
         rf" (axis cs:12.15,{end['conditioned']:.1f}) {{conditioned}};")
L.append(rf"\node[font=\scriptsize, fignaive, anchor=west] at"
         rf" (axis cs:12.15,{end['naive']:.1f}) {{naive}};")
L.append(rf"\node[font=\scriptsize, figmuted, anchor=west] at"
         rf" (axis cs:12.15,{end['ungrounded']:.1f}) {{ungrounded \chat{{}}}};")
L.append(rf"\node[font=\scriptsize, fignaive, anchor=south] at"
         rf" (axis cs:8,{data['unmasked'][0][1] + 2:.1f}) {{unmasked}};")

L.append(r"\end{axis}")
L.append(r"\end{tikzpicture}")

with open(OUT, "w") as f:
    f.write("\n".join(L) + "\n")
print("wrote", OUT)
