#!/usr/bin/env python3
"""Fig: on-robot counterfactual dose sweep (paper §VI, fig:live) — pgfplots.

Emits paper/figs/live_counterfactuals.tex (a tikzpicture, \\input from
6_robot.tex) so the figure is typeset in the paper's own font. Two panels
sharing the dose axis:
  (a) action response delta-dz vs real, conditioned vs naive — the crossover
  (b) FiLM modulation magnitude (mean |gamma|, |beta|) — the pathway responding

Supersedes make_live_counterfactuals.py (matplotlib, 3-panel draft; the c-hat
panel was dropped 08-14 — true by construction, not evidence).

Data: LGES/vla_training/live_film_probes/smolvla_film_0729_prefix_mask1_recal_fromnaive/
  run3 (fair dose, 10 poses)  st_fz+3N / st_fz+6N
  run4 (high dose,  3 poses)  st_fz+6N / st_fz+9N / st_fz+12N
st_* = raw-state transplants, drift-shifted so both policies receive the same
physical dose. Paper quotes run4 means +1.19/+4.59/+8.56 film vs
+1.34/+3.18/+4.18 naive — reproduced here from the JSONs.
"""
import json

import numpy as np

BASE = ("/home/maverick/Humanoid/Dexmate/LGES/vla_training/live_film_probes/"
        "smolvla_film_0729_prefix_mask1_recal_fromnaive")
OUT = ("/home/maverick/Humanoid/Dexmate/Research/Paper_writing/FiLM/paper/figs/"
       "live_counterfactuals.tex")

RUNS = [  # (json, pgf mark, [(dose_N, scenario_key), ...])
    (f"{BASE}/run3_0806_fair-dose_10poses_VALID/20260806-152448_live_film_authority.json",
     "*", [(3, "st_fz+3N"), (6, "st_fz+6N")]),
    (f"{BASE}/run4_0806_high-dose_fz6-9-12N_3poses_VALID/20260806-152957_live_film_authority.json",
     "square*", [(6, "st_fz+6N"), (9, "st_fz+9N"), (12, "st_fz+12N")]),
]


def load(path, keys):
    d = json.load(open(path))
    out = {"doses": [], "film": [], "naive": [], "gam": [], "bet": []}
    for dose, key in keys:
        f_dz, n_dz, g, b = [], [], [], []
        for p in d["poses"]:
            s, base = p["scenarios"], p["baseline_scenarios"]
            f_dz.append((s[key]["dpos_m"][2] - s["real"]["dpos_m"][2]) * 1000)
            n_dz.append((base[key]["dpos_m"][2] - base["real"]["dpos_m"][2]) * 1000)
            g.append(s[key]["film"]["gamma"]["abs_mean"])
            b.append(s[key]["film"]["beta"]["abs_mean"])
        out["doses"].append(dose)
        out["film"].append(np.array(f_dz))
        out["naive"].append(np.array(n_dz))
        out["gam"].append(np.mean(g))
        out["bet"].append(np.mean(b))
    out["descent"] = float(np.mean(
        [-p["scenarios"]["real"]["dpos_m"][2] * 1000 for p in d["poses"]]))
    return out


runs = [(mark, load(path, keys)) for path, mark, keys in RUNS]
descent_ref = runs[1][1]["descent"]        # run4 mean own descent per frame
r4 = runs[1][1]
end_film, end_naive = r4["film"][-1].mean(), r4["naive"][-1].mean()


def coords(pairs, fmt="({:.2f},{:.2f})"):
    return " ".join(fmt.format(x, y) for x, y in pairs)


def scatter(dose, vals, shift):
    """Deterministic jitter: poses fan out evenly around the dose tick."""
    off = np.linspace(-0.14, 0.14, len(vals)) + shift
    return coords(zip(dose + off, vals))


L = []
L.append("% AUTO-GENERATED by scripts/make_live_counterfactuals_pgf.py — do not edit.")
L.append("% Data: LGES/vla_training/live_film_probes/... run3 (10 poses) + run4 (3 poses),")
L.append("% st_* raw-state transplants; see the script header for provenance.")
L.append(r"\definecolor{figcond}{HTML}{0072B2}")
L.append(r"\definecolor{fignaive}{HTML}{D55E00}")
L.append(r"\definecolor{figmuted}{HTML}{767676}")
L.append(r"\begin{tikzpicture}")
L.append(r"\begin{groupplot}[")
L.append(r"  group style={group size=1 by 2, vertical sep=4.5mm,")
L.append(r"    xlabels at=edge bottom, xticklabels at=edge bottom},")
L.append(r"  width=7.9cm, xmin=2.2, xmax=13.9, xtick={3,6,9,12},")
L.append(r"  tick label style={font=\scriptsize}, label style={font=\scriptsize},")
L.append(r"  axis x line*=bottom, axis y line*=left,")
L.append(r"  axis line style={figmuted!60, line width=0.4pt},")
L.append(r"  tick style={figmuted!60},")
L.append(r"  ymajorgrids, grid style={figmuted!22, line width=0.3pt},")
L.append(r"  clip=false, legend style={draw=none, fill=none, font=\scriptsize,")
L.append(r"    legend cell align=left, at={(0.05,0.98)}, anchor=north west},")
L.append(r"]")

# --- (a) response ------------------------------------------------------------
L.append(r"\nextgroupplot[height=5.2cm, ymin=-0.9, ymax=11.4,")
L.append(r"  ylabel={response $\Delta d_z$ (mm/frame)}]")
L.append(r"\addlegendimage{figcond, line width=0.9pt}\addlegendentry{conditioned}")
L.append(r"\addlegendimage{fignaive, line width=0.9pt}\addlegendentry{naive}")
for mark, r in runs:
    for series, color, shift in (("film", "figcond", -0.03), ("naive", "fignaive", 0.03)):
        for dose, vals in zip(r["doses"], r[series]):
            L.append(rf"\addplot[only marks, mark=*, mark size=0.6pt, {color},"
                     rf" opacity=0.28, forget plot] coordinates {{"
                     + scatter(dose, vals, shift) + "};")
for mark, r in runs:
    for series, color in (("film", "figcond"), ("naive", "fignaive")):
        means = [(d, v.mean()) for d, v in zip(r["doses"], r[series])]
        L.append(rf"\addplot[{color}, line width=0.9pt, mark={mark},"
                 rf" mark size=1.4pt, mark options={{fill={color},"
                 rf" draw=white, line width=0.3pt}}, forget plot]"
                 rf" coordinates {{{coords(means)}}};")
L.append(rf"\addplot[figmuted, dash pattern=on 3pt off 2pt, line width=0.5pt,"
         rf" forget plot] coordinates {{(2.2,{descent_ref:.2f}) (13.9,{descent_ref:.2f})}};")
L.append(rf"\node[font=\tiny, figmuted, anchor=south west] at (axis cs:2.5,{descent_ref:.2f})"
         rf" {{own mean descent (net retreat above)}};")
L.append(rf"\node[font=\scriptsize, figcond, anchor=west, fill=white, inner sep=1pt]"
         rf" at (axis cs:12.35,{end_film:.2f}) {{$+{end_film:.1f}$}};")
L.append(rf"\node[font=\scriptsize, fignaive, anchor=west, fill=white, inner sep=1pt]"
         rf" at (axis cs:12.35,{end_naive:.2f}) {{$+{end_naive:.1f}$}};")
L.append(r"\node[font=\scriptsize\bfseries, anchor=north west] at"
         r" (rel axis cs:0.0,0.99) {(a)};")

# --- (b) FiLM modulation ------------------------------------------------------
L.append(r"\nextgroupplot[height=3.6cm, ymin=0, ymax=0.30, ytick={0,0.1,0.2,0.3},")
L.append(r"  ylabel={FiLM gain (mean $|\cdot|$)},")
L.append(r"  xlabel={transplanted normal-force dose (N)}]")
for mark, r in runs:
    open_mark = mark.rstrip("*")   # open variant for the beta series
    gam = list(zip(r["doses"], r["gam"]))
    bet = list(zip(r["doses"], r["bet"]))
    L.append(rf"\addplot[figcond, line width=0.9pt, mark={mark}, mark size=1.4pt,"
             rf" mark options={{fill=figcond, draw=white, line width=0.3pt}},"
             rf" forget plot] coordinates {{{coords(gam, '({:.2f},{:.3f})')}}};")
    L.append(rf"\addplot[figcond, line width=0.7pt, dash pattern=on 3pt off 2pt,"
             rf" mark={open_mark}, mark size=1.3pt, mark options={{solid,"
             rf" fill=white, line width=0.5pt}}, forget plot]"
             rf" coordinates {{{coords(bet, '({:.2f},{:.3f})')}}};")
L.append(rf"\node[font=\scriptsize, figcond, anchor=west] at"
         rf" (axis cs:12.35,{r4['gam'][-1]:.3f}) {{$|\gamma|$}};")
L.append(rf"\node[font=\scriptsize, figcond, anchor=west] at"
         rf" (axis cs:12.35,{r4['bet'][-1]:.3f}) {{$|\beta|$}};")
L.append(r"\node[font=\scriptsize\bfseries, anchor=north west] at"
         r" (rel axis cs:0.0,0.99) {(b)};")

L.append(r"\end{groupplot}")
L.append(r"\end{tikzpicture}")

with open(OUT, "w") as f:
    f.write("\n".join(L) + "\n")
print("wrote", OUT)
print(f"  descent ref {descent_ref:.2f} mm, ends film +{end_film:.2f} / naive +{end_naive:.2f}")
