#!/usr/bin/env python3
"""Fig: on-robot counterfactual dose sweep (paper §VI, fig:live) — pgfplots.

Emits paper/figs/live_counterfactuals.tex (a tikzpicture, \\input from
6_robot.tex) so the figure is typeset in the paper's own font. Two panels
sharing the dose axis:
  (a) action response delta-dz vs real, conditioned vs naive — the crossover
  (b) FiLM modulation magnitude (mean |gamma|, |beta|) — the pathway responding

Supersedes make_live_counterfactuals.py (matplotlib, 3-panel draft; the c-hat
panel was dropped 08-14 — true by construction, not evidence).

Data: LGES/vla_training/live_film_probes/smolvla_film_0729_prefix_mask1_recal_fromnaive/
  +3N          run3 (fair dose), restricted to the three poses whose staged
               clearance matches run4 (5/3/1 cm) — n uniform across all doses
               (08-14 user decision; the 10-pose +3N means were film +0.46 /
               naive +0.69, the matched-3 means are +0.43 / +1.30 — the naive
               shift comes from its outlier pose at 5 cm, conservative for the
               crossover claim)
  +6/+9/+12N   run4 (high dose, 3 poses)
st_* = raw-state transplants, drift-shifted so both policies receive the same
physical dose. Paper quotes run4 means +1.19/+4.59/+8.56 film vs
+1.34/+3.18/+4.18 naive — reproduced here from the JSONs.
"""
import json

import numpy as np

BASE = ("/home/maverick/Humanoid/Dexmate/LGES/vla_training/live_film_probes/"
        "smolvla_film_0729_prefix_mask1_recal_fromnaive")
OUT = ("/home/maverick/Humanoid/Dexmate/Research/Paper_writing/FiLM/paper/figs/"
       "live_counterfactuals.tex")

MATCH_CLEARANCES = (0.05, 0.03, 0.01)    # run4's staged poses
SOURCES = [  # (json, clearance filter, [(dose_N, scenario_key), ...])
    (f"{BASE}/run3_0806_fair-dose_10poses_VALID/20260806-152448_live_film_authority.json",
     MATCH_CLEARANCES, [(3, "st_fz+3N")]),
    (f"{BASE}/run4_0806_high-dose_fz6-9-12N_3poses_VALID/20260806-152957_live_film_authority.json",
     None, [(6, "st_fz+6N"), (9, "st_fz+9N"), (12, "st_fz+12N")]),
]

doses, film, naive, gam, bet = [], [], [], [], []
descent_ref = None
for path, clearances, keys in SOURCES:
    d = json.load(open(path))
    poses = [p for p in d["poses"]
             if clearances is None or p["clearance_m"] in clearances]
    assert len(poses) == 3, (path, [p["clearance_m"] for p in poses])
    for dose, key in keys:
        doses.append(dose)
        film.append(np.mean([(p["scenarios"][key]["dpos_m"][2]
                              - p["scenarios"]["real"]["dpos_m"][2]) * 1000
                             for p in poses]))
        naive.append(np.mean([(p["baseline_scenarios"][key]["dpos_m"][2]
                               - p["baseline_scenarios"]["real"]["dpos_m"][2]) * 1000
                              for p in poses]))
        gam.append(np.mean([p["scenarios"][key]["film"]["gamma"]["abs_mean"]
                            for p in poses]))
        bet.append(np.mean([p["scenarios"][key]["film"]["beta"]["abs_mean"]
                            for p in poses]))
    if clearances is None:
        # net-retreat reference = the STRICTER of the two policies' own mean
        # descent steps (run4: film 4.12, naive 4.27 mm — within 4%). Above
        # the line = net retreat under either baseline; at film's own 4.12
        # the naive endpoint (+4.18) would cross a threshold that is not its
        # own (its own is 4.27, which it does not reach).
        descent_ref = max(
            float(np.mean([-p["scenarios"]["real"]["dpos_m"][2] * 1000
                           for p in poses])),
            float(np.mean([-p["baseline_scenarios"]["real"]["dpos_m"][2] * 1000
                           for p in poses])))


def coords(xs, ys, fmt="({:.2f},{:.2f})"):
    return " ".join(fmt.format(x, y) for x, y in zip(xs, ys))


L = []
L.append("% AUTO-GENERATED by scripts/make_live_counterfactuals_pgf.py — do not edit.")
L.append("% Data: LGES/vla_training/live_film_probes/... run3 (+3N, clearance-matched")
L.append("% poses) + run4 (+6/9/12N); st_* raw-state transplants; see script header.")
L.append(r"\definecolor{figcond}{HTML}{0072B2}")
L.append(r"\definecolor{fignaive}{HTML}{D55E00}")
L.append(r"\definecolor{figmuted}{HTML}{767676}")
L.append(r"\begin{tikzpicture}")
L.append(r"\begin{groupplot}[")
L.append(r"  group style={group size=1 by 2, vertical sep=4.5mm,")
L.append(r"    xlabels at=edge bottom, xticklabels at=edge bottom},")
L.append(r"  width=7.9cm, xmin=2.2, xmax=13.9, xtick={3,6,9,12},")
L.append(r"  tick label style={font=\scriptsize}, label style={font=\scriptsize},")
L.append(r"  axis x line*=bottom, axis y line*=left,")
L.append(r"  axis line style={figmuted!60, line width=0.4pt},")
L.append(r"  tick style={figmuted!60},")
L.append(r"  ymajorgrids, grid style={figmuted!22, line width=0.3pt},")
L.append(r"  clip=false, legend style={draw=none, fill=none, font=\scriptsize,")
L.append(r"    legend cell align=left, at={(0.05,0.98)}, anchor=north west},")
L.append(r"]")

# --- (a) response ------------------------------------------------------------
L.append(r"\nextgroupplot[height=5.2cm, ymin=-0.4, ymax=9.4,")
L.append(r"  ylabel={response $\Delta d_z$ (mm/frame)}]")
for series, color, name in ((film, "figcond", "conditioned"),
                            (naive, "fignaive", "naive")):
    L.append(rf"\addplot[{color}, line width=0.9pt, mark=*, mark size=1.4pt,"
             rf" mark options={{fill={color}, draw=white, line width=0.3pt}}]"
             rf" coordinates {{{coords(doses, series)}}};")
    L.append(rf"\addlegendentry{{{name}}}")
L.append(rf"\addplot[figmuted, dash pattern=on 3pt off 2pt, line width=0.5pt,"
         rf" forget plot] coordinates {{(2.2,{descent_ref:.2f}) (13.9,{descent_ref:.2f})}};")
L.append(rf"\node[font=\tiny, figmuted, anchor=south west] at (axis cs:2.5,{descent_ref:.2f})"
         rf" {{own mean descent (net retreat above)}};")
L.append(rf"\node[font=\scriptsize, figcond, anchor=west, fill=white, inner sep=1pt]"
         rf" at (axis cs:12.35,{film[-1]:.2f}) {{$+{film[-1]:.1f}$}};")
L.append(rf"\node[font=\scriptsize, fignaive, anchor=west, fill=white, inner sep=1pt]"
         rf" at (axis cs:12.35,{naive[-1]:.2f}) {{$+{naive[-1]:.1f}$}};")
L.append(r"\node[font=\scriptsize\bfseries, anchor=north west] at"
         r" (rel axis cs:0.0,0.99) {(a)};")

# --- (b) FiLM modulation ------------------------------------------------------
L.append(r"\nextgroupplot[height=3.6cm, ymin=0, ymax=0.30, ytick={0,0.1,0.2,0.3},")
L.append(r"  ylabel={FiLM gain (mean $|\cdot|$)},")
L.append(r"  xlabel={transplanted normal-force dose (N)}]")
L.append(rf"\addplot[figcond, line width=0.9pt, mark=*, mark size=1.4pt,"
         rf" mark options={{fill=figcond, draw=white, line width=0.3pt}},"
         rf" forget plot] coordinates {{{coords(doses, gam, '({:.2f},{:.3f})')}}};")
L.append(rf"\addplot[figcond, line width=0.7pt, dash pattern=on 3pt off 2pt,"
         rf" mark=o, mark size=1.3pt, mark options={{solid, fill=white,"
         rf" line width=0.5pt}}, forget plot]"
         rf" coordinates {{{coords(doses, bet, '({:.2f},{:.3f})')}}};")
L.append(rf"\node[font=\scriptsize, figcond, anchor=west] at"
         rf" (axis cs:12.35,{gam[-1]:.3f}) {{$|\gamma|$}};")
L.append(rf"\node[font=\scriptsize, figcond, anchor=west] at"
         rf" (axis cs:12.35,{bet[-1]:.3f}) {{$|\beta|$}};")
L.append(r"\node[font=\scriptsize\bfseries, anchor=north west] at"
         r" (rel axis cs:0.0,0.99) {(b)};")

L.append(r"\end{groupplot}")
L.append(r"\end{tikzpicture}")

with open(OUT, "w") as f:
    f.write("\n".join(L) + "\n")
print("wrote", OUT)
print("  doses", doses)
print("  film ", np.round(film, 2), " naive", np.round(naive, 2))
print(f"  descent ref {descent_ref:.2f} mm")
