#!/usr/bin/env python3
"""Fig: contact force on the robot (paper §V-D, fig:forcetraces) — pgfplots.

Emits paper/figs/robot_force_traces.tex (a tikzpicture, \\input from 6_robot.tex) so the
figure is typeset in the paper's own font, like dose_response.tex / live_counterfactuals.tex.
Supersedes make_force_traces.py (matplotlib PDF; kept for reference).

Same data and same two representative trials as the matplotlib version:
  naive  : rollouts/smolvla_naive_0729/*142623*            (external abort, marked x)
  FiLM   : rollouts/smolvla_film_0729_prefix_mask1/L5/20260730-170039_r03_ep0000_case_pick
           (L5 pick at the median peak, 2.5 N)
Contact force = |F| - meta.baseline_force_n over the interaction window (before lift begins:
frame after the last time EE z is within 20 mm of its deepest point; metric decision 08-11).
Traces aligned at peak force (t=0), 8 s before the peak shown.
"""
import glob, json, math, os

import numpy as np

_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../../.."))  # .../Dexmate
BASE = os.path.join(_ROOT, "LGES/vla_training/rollouts")
OUT = os.path.join(_ROOT, "Research/Paper_writing/FiLM/paper/figs/robot_force_traces.tex")
LIMIT, W_PRE, W_POST = 15.0, 8.0, 0.0


def load(run_dir):
    meta = json.load(open(os.path.join(run_dir, "meta.json")))
    t, f, z = [], [], []
    for line in open(os.path.join(run_dir, "states.jsonl")):
        d = json.loads(line)
        w = d["wrench"]
        t.append(d["t"])
        f.append(math.sqrt(w["fx"] ** 2 + w["fy"] ** 2 + w["fz"] ** 2) - meta["baseline_force_n"])
        z.append(d["ee"]["pos"][2])
    t, f, z = np.array(t) - t[0], np.array(f), np.array(z)
    lift = len(f)
    below = np.nonzero(z < z.min() + 0.020)[0]
    if len(below):
        lift = int(below[-1]) + 1
    return t[:lift], f[:lift]


def window(t, f):
    pk = int(np.argmax(f))
    tt = t - t[pk]
    m = (tt >= -W_PRE) & (tt <= W_POST)
    return tt[m], f[m]


naive_dir = next(d for d in sorted(glob.glob(f"{BASE}/smolvla_naive_0729/2026*")) if "142623" in d)
cond_dir = f"{BASE}/smolvla_film_0729_prefix_mask1/L5/20260730-170039_r03_ep0000_case_pick"
tn, fn = window(*load(naive_dir))
tc, fc = window(*load(cond_dir))


def coords(t, f):
    return " ".join(f"({x:.3f},{y:.2f})" for x, y in zip(t, f))


L = []
L.append("% AUTO-GENERATED by scripts/make_force_traces_pgf.py — do not edit.")
L.append(f"% Data: {os.path.relpath(naive_dir, _ROOT)} (naive) / {os.path.relpath(cond_dir, _ROOT)} (FiLM).")
L.append(r"\definecolor{figcond}{HTML}{0072B2}")
L.append(r"\definecolor{fignaive}{HTML}{D55E00}")
L.append(r"\definecolor{figmuted}{HTML}{767676}")
L.append(r"\begin{tikzpicture}")
L.append(r"\begin{axis}[")
L.append(r"  width=8.6cm, height=5.0cm, xmin=-8, xmax=0.4, ymin=-1.2, ymax=20,")
L.append(r"  xtick={-8,-6,-4,-2,0}, ytick={0,5,10,15,20},")
L.append(r"  xlabel={time from peak force (s)}, ylabel={contact force (N)},")
L.append(r"  tick label style={font=\scriptsize}, label style={font=\scriptsize},")
L.append(r"  axis x line*=bottom, axis y line*=left,")
L.append(r"  axis line style={figmuted!60, line width=0.4pt},")
L.append(r"  tick style={figmuted!60},")
L.append(r"  ymajorgrids, grid style={figmuted!22, line width=0.3pt},")
L.append(r"  clip=false, legend style={draw=none, fill=none, font=\scriptsize,")
L.append(r"    legend cell align=left, at={(0.02,0.98)}, anchor=north west, row sep=-1.5pt},")
L.append(r"]")
L.append(r"\addplot[figmuted!90, dash pattern=on 4pt off 3pt, line width=0.5pt, forget plot] coordinates {(-8,15) (0.4,15)};")
L.append(r"\node[font=\tiny, figmuted, anchor=south west] at (axis cs:-4.0,15.2) {15\,N abort limit};")
L.append(rf"\addplot[figcond, line width=1.0pt] coordinates {{{coords(tc, fc)}}};")
L.append(r"\addlegendentry{FiLM (ours)}")
L.append(rf"\addplot[fignaive, line width=1.0pt] coordinates {{{coords(tn, fn)}}};")
L.append(r"\addlegendentry{naive (aborted $\times$)}")
L.append(rf"\addplot[only marks, mark=x, mark size=2.6pt, fignaive, line width=1.1pt, forget plot] coordinates {{({tn[-1]:.3f},{fn[-1]:.2f})}};")
L.append(r"\end{axis}")
L.append(r"\end{tikzpicture}")
open(OUT, "w").write("\n".join(L) + "\n")
print(f"naive n={len(tn)} peak={fn.max():.2f}N  FiLM n={len(tc)} peak={fc.max():.2f}N  ->", OUT)
