#!/usr/bin/env python3
"""Fig: offline dose-response sweep (paper §V, fig:doseresponse) — pgfplots.

Emits paper/figs/dose_response.tex (a tikzpicture, \\input from 5_offline.tex).
One panel: cancellation of the policy's own commanded descent (%) vs the
transplanted first-contact wrench rescaled to 8/10/12 N (probe P3, --swap fcscale).

Data: LGES/vla_training/probes/0729_state_<model>_ramp<N>.txt, "ALL frames" row
of the decomposition block (n=245 for naive-best/conditioned, n=739 otherwise —
the same rows Table tab:probes / tab:ablation quote: naive +1.41→+1.12 of own
−3.94; conditioned +1.20→+4.40 of own −3.84; wrench-kept +1.57→+1.12 of own
−3.77; shuffled −0.06→−0.11). Percent = dTotal / |dz(own)| × 100. The
shuffled control's own descent here is the ramp file's (−3.78), not the pc_r12
value the table footnotes; the curve is ≈0 either way.
09-14: π0/π0.5 series removed (paper no longer discusses their dose-response).
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]          # .../Dexmate
PROBES = ROOT / "LGES/vla_training/probes"
OUT = Path(__file__).resolve().parents[1] / "paper/figs/dose_response.tex"

# (legend label, file stem, doses, color, style)
SERIES = [
    ("FiLM (ours)",                    "fromnaive_best", (8, 12), "figcond", "solid, line width=1.0pt, mark=*"),
    ("naive (raw wrench)",             "naive",          (8, 10, 12), "fignaive", "solid, line width=1.0pt, mark=*"),
    ("FiLM, wrench kept",              "mask0fn_main",   (8, 12), "figkept", "solid, line width=0.8pt, mark=triangle*"),
    ("FiLM, mask, shuffled $\\hat{c}$", "v1_main",       (8, 12), "figshuf", "solid, line width=0.8pt, mark=diamond*"),
]

ROW = re.compile(r"ALL frames\s*:\s*n=\s*(\d+)\s+dz\(own\)=\s*([-+]?\d+\.\d+)mm\s+dTotal=\s*([-+]?\d+\.\d+)mm")


def read(stem, dose):
    name = f"0729_state_{stem}_ramp{dose}.txt"
    for line in (PROBES / name).read_text().splitlines():
        m = ROW.search(line)
        if m:
            n, own, dtot = int(m.group(1)), float(m.group(2)), float(m.group(3))
            return n, own, dtot
    raise SystemExit(f"no ALL-frames row in {name}")


L = []
L.append("% AUTO-GENERATED by scripts/make_dose_response_pgf.py — do not edit.")
L.append("% Data: LGES/vla_training/probes/0729_state_*_ramp{8,10,12}.txt, ALL-frames row.")
L.append(r"\definecolor{figcond}{HTML}{0072B2}")
L.append(r"\definecolor{fignaive}{HTML}{D55E00}")
L.append(r"\definecolor{figkept}{HTML}{CC79A7}")
L.append(r"\definecolor{figshuf}{HTML}{009E73}")
L.append(r"\definecolor{figmuted}{HTML}{767676}")
L.append(r"\begin{tikzpicture}")
L.append(r"\begin{axis}[")
L.append(r"  width=8.6cm, height=5.6cm, xmin=7.4, xmax=12.6, xtick={8,10,12},")
L.append(r"  ymin=-12, ymax=128, ytick={0,25,50,75,100,125},")
L.append(r"  xlabel={transplanted first-contact wrench, rescaled (N)},")
L.append(r"  ylabel={cancellation of own descent (\%)},")
L.append(r"  tick label style={font=\scriptsize}, label style={font=\scriptsize},")
L.append(r"  axis x line*=bottom, axis y line*=left,")
L.append(r"  axis line style={figmuted!60, line width=0.4pt},")
L.append(r"  tick style={figmuted!60},")
L.append(r"  ymajorgrids, grid style={figmuted!22, line width=0.3pt},")
L.append(r"  clip=false, legend style={draw=none, fill=none, font=\scriptsize,")
L.append(r"    legend cell align=left, at={(0.02,0.98)}, anchor=north west, row sep=-1.5pt},")
L.append(r"]")
# reference lines
L.append(r"\addplot[figmuted, dash pattern=on 3pt off 2pt, line width=0.5pt, forget plot] coordinates {(7.4,100) (12.6,100)};")
L.append(r"\node[font=\tiny, figmuted, anchor=south east] at (axis cs:12.6,100) {full stop (retreat above)};")
L.append(r"\addplot[figmuted!70, line width=0.4pt, forget plot] coordinates {(7.4,0) (12.6,0)};")
# demonstrated-range shading: press targets drawn from [8, 15] N peak near the low end;
# mark the transplant reference (8 N = measured first-contact magnitude)
L.append(r"\node[font=\tiny, figmuted, anchor=west] at (axis cs:8.08,-9.5) {8\,N = measured first-contact magnitude};")

summary = []
for label, stem, doses, color, style in SERIES:
    pts = []
    for d in doses:
        n, own, dtot = read(stem, d)
        pct = dtot / abs(own) * 100
        pts.append((d, pct))
        summary.append(f"{stem:16s} {d:2d}N n={n} own={own:+.2f} dTot={dtot:+.2f} -> {pct:6.1f}%")
    coords = " ".join(f"({d},{p:.1f})" for d, p in pts)
    L.append(rf"\addplot[{color}, {style}, mark size=1.5pt, mark options={{solid, fill={color}, draw=white, line width=0.3pt}}] coordinates {{{coords}}};")
    L.append(rf"\addlegendentry{{{label}}}")
    if stem == "fromnaive_best":
        L.append(rf"\node[font=\scriptsize, {color}, anchor=west, fill=white, inner sep=1pt] at (axis cs:12.12,{pts[-1][1]:.1f}) {{${pts[-1][1]:.0f}\%$}};")
    if stem == "naive":
        L.append(rf"\node[font=\scriptsize, {color}, anchor=west, fill=white, inner sep=1pt] at (axis cs:12.12,{pts[-1][1]:.1f}) {{${pts[-1][1]:.0f}\%$}};")
L.append(r"\end{axis}")
L.append(r"\end{tikzpicture}")

OUT.write_text("\n".join(L) + "\n")
print("\n".join(summary))
print("wrote", OUT)
